AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs-lambda-app

Resources:
  # This is an SQS queue with all default configuration properties.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "lambda-test"

  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SQSPayloadLogger
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs18.x
      Handler: src/sqs-payload-logger.sqsPayloadLoggerHandler
      # This property associates this Lambda function with the SQS queue defined above, so that whenever the queue
      # receives a message, the Lambda function is invoked
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      # MemorySize: 128 # default
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds.
      # Policies: # default
      #   - AWSLambdaBasicExecutionRole
