AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 30

# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
Resources:
  Lambda1Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api

  Lambda2Sqs:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 65 # should be greater that lambda timeout

  Lambda1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-1/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SQS_URL: !Ref Lambda2Sqs # Gets SQS Queue URL
      Events:
        Lambda1ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: Lambda1Api

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-2/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Timeout: 60
      Events:
        lambda2invoker:
          Type: SQS
          Properties:
            Queue: !GetAtt Lambda2Sqs.Arn
            BatchSize: 1

Outputs:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
  Lambda1Api:
    Value: !Sub 'https://${Lambda1Api}.execute-api.${AWS::Region}.amazonaws.com/api/'

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
  Lambda1:
    Description: 'Lambda1 Function ARN'
    Value: !GetAtt Lambda1.Arn

  Lambda1IamRole:
    Description: 'Implicit IAM Role created for Lambda1 function'
    Value: !GetAtt Lambda1Role.Arn
