#!/usr/bin/env bash

# -s: return 0 if executable exists, 1 otherwise
if ! which -s sam; then
  echo "sam not found. Try . virtualenv/bin/activate"
  exit 1
fi

# If we don't have 2 arguments passed,
# print usage and exit with error code
if [ $# -lt 1 ]; then
  echo >&2 "
Usage: ./deploy <stack_name>

e.g. ./deploy sam-app 
"
  exit 1
fi

cd "$1"

# bash -x deploy.sh: prints each command of a script before executing it

# -x: print each command before executing it until `set +x` is called
set -x

# exit when any command fails
set -e

sam build

sam deploy \
  --stack-name $stack_name \
  --capabilities CAPABILITY_IAM

cd -
