AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dmarc scheduler

Resources:
  ScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 30
      Architectures:
        - x86_64
      Environment:
        Variables:
          DMARC_LOG_GROUP_NAME: /aws/lambda/dmarc-DmarcFunction-JswJhstTvPnZ
      Layers:
        - !Ref Layer
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies:
        #  https://serverlessland.com/patterns/lambda-ses
        - SESCrudPolicy:
            IdentityName: '*'
        - Statement:
            - Sid: DmarcSchedulePolicy
              Effect: Allow
              Action:
                - logs:StartQuery
                - logs:GetQueryResults
              Resource: '*'

  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: dmarc-schedule
      ScheduleExpression: 'rate(10 minutes)'
      # ScheduleExpression: 'cron(0 0 * * ? *)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt ScheduleFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn

  ScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ScheduleRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt ScheduleFunction.Arn

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: dmarc schedule layer
      ContentUri: layer
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
