AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dmarc processing

Resources:
  VPC:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc/template.yaml

  Redis:
    Type: AWS::Serverless::Application
    Properties:
      Location: redis/template.yaml
      Parameters:
        PrivateSubnetId: !GetAtt VPC.Outputs.PrivateSubnetId
        SecurityGroupId: !GetAtt VPC.Outputs.SecurityGroupId

  Kinesis:
    Type: AWS::Serverless::Application
    Properties:
      Location: kinesis/template.yaml

  S3SQS:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3_sqs/template.yaml

  Lambda:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda/template.yaml
      Parameters:
        PrivateSubnetId: !GetAtt VPC.Outputs.PrivateSubnetId
        SecurityGroupId: !GetAtt VPC.Outputs.SecurityGroupId
        ElastiCacheRedisClusterEndpoint: !GetAtt Redis.Outputs.ElastiCacheRedisClusterEndpoint
        KinesisStreamName: !GetAtt Kinesis.Outputs.KinesisStreamName
        KinesisStreamArn: !GetAtt Kinesis.Outputs.KinesisStreamArn
        DmarcBucketName: !GetAtt S3SQS.Outputs.DmarcBucketName
        DmarcQueueArn: !GetAtt S3SQS.Outputs.DmarcQueueArn

  Insight:
    Type: AWS::Serverless::Application
    Properties:
      Location: template_insight.yaml
      Parameters:
        # Env: !Ref Env
        # DmarcFunctionName: !GetAtt Dmarc.Outputs.DmarcFunctionName
        # RecordFunctionName: !GetAtt Dmarc.Outputs.RecordFunctionName
        # DmarcLayerArn: !GetAtt Dmarc.Outputs.DmarcLayerArn

Outputs:
  PrivateSubnetId:
    Value: !GetAtt VPC.Outputs.PrivateSubnetId
  SecurityGroupId:
    Value: !GetAtt VPC.Outputs.SecurityGroupId
  ElastiCacheRedisClusterEndpoint:
    Value: !GetAtt Redis.Outputs.ElastiCacheRedisClusterEndpoint
  DmarcBucketName:
    Value: !GetAtt S3SQS.Outputs.DmarcBucketName
  DmarcQueueUrl:
    Value: !GetAtt S3SQS.Outputs.DmarcQueueUrl
