AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: send records to kinesis

Parameters:
  RecordQueueArn:
    Type: String
  RecordBucketName:
    Type: String

Resources:
  KinesisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: nodejs18.x
      Handler: app.handler
      MemorySize: 200
      Timeout: 120
      Layers:
        - !Ref AppLayer
      AutoPublishAlias: live
      Architectures:
        - x86_64
      Environment:
        Variables:
          RECORDBUCKET_NAME: !Ref RecordBucketName
          KINESIS_ARN: !GetAtt Stream.Arn
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref RecordBucketName
        - KinesisCrudPolicy:
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#kinesis-crud-policy
            StreamName: !Ref Stream
      # Events:
      #   KinesisFunctionInvoker:
      #     Type: SQS
      #     Properties:
      #       Queue: !Ref RecordQueueArn
      #       BatchSize: 1

  Stream:
    Type: AWS::Kinesis::Stream
    Properties:
      StreamModeDetails:
        # StreamMode: ON_DEMAND
        StreamMode: PROVISIONED
      ShardCount: 10

  AppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: app specific deps
      ContentUri: layer
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

Outputs:
  KinesisFunction:
    Value: !GetAtt KinesisFunction.Arn
  KinesisFunctionIamRole:
    Description: 'Implicit IAM Role created for KinesisFunction'
    Value: !GetAtt KinesisFunctionRole.Arn
  Stream:
    Description: 'Kinesis Stream'
    Value: !Ref Stream
  AppLayer:
    Value: !Ref AppLayer
