version = 0.1

[default]
[default.global.parameters]
stack_name = "dmarc"

[default.deploy.parameters]
stack_name = "dmarc"
resolve_s3 = true
s3_prefix = "dmarc"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
