# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "dmarc"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "dmarc"
region = "us-east-2"
image_repositories = []
parameter_overrides = [
  "DmarcBucketName=inboxmonster-dev-dmarc-isolated-us-east-2-datalake",
  "DmarcQueueUrl=https://sqs.us-east-2.amazonaws.com/524978277775/inboxmonster-dev-dmarc-isolated-us-east-2-datalake-email",
  "DmarcQueueArn=arn:aws:sqs:us-east-2:524978277775:inboxmonster-dev-dmarc-isolated-us-east-2-datalake-email",
  "KinesisStreamArn=arn:aws:kinesis:us-east-2:524978277775:stream/inboxmonster-dev-dmarc-isolated-us-east-2-stream",
  "KinesisStreamName=inboxmonster-dev-dmarc-isolated-us-east-2-stream",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
stack_name = "dmarc"

